=head1 NAME

diaspora-rss - is a daemon which posts rss feeds to an diaspora account.

=head1 SYNOPSIS

 Usage: script/diaspora-rss [-vhcdpuPD]

 Options:
 -h --help                      print this usage text
 -v --version                   print the program version
 -c <file> | --config=<file>    use config file <file> instead of the default
 -u <user> | --user=<user>      use <user> to login to diaspora
 -P <pass> | --passwd=<pass>    use <pass> to login to diaspora
 -p <pod>  | --pod=<pod>        use <pod> uri as diaspora pod
 -d        | --debug            do not fork into background and print logs to stdout
 -D <db>   | --database=<db>    use sqlite db <db> file to store feed information

=head1 CONFIG FILE

Config file (if not specified via commandline) might be located in one of the
following locations. script/diaspora-rss looks for them in this order:

 ~/.diaspora-rss
 /etc/diaspora-rss.conf
 /usr/local/etc/diaspora-rss.conf

=head1 AUTHOR

Oliver.

=head1 VERSION

0.01

=cut
